import { AllResponse, Vacancy } from "./definitions";

export const vacancies: AllResponse<Vacancy> = {
  "items": [
      {
          "id": 1,
          "active": false,
          "external_id": "aedc21ec-6b86-4b14-91ff-0d29c2b9e8aa",
          "company_name": "Nixon, Perez and Cruz",
          "title": "Make",
          "salary": "3364-10666",
          "location": "Andrewchester",
          "speciality": "Java",
          "internship": true,
          "remote": true,
          "url": "https://morris-brown.org/",
          "description": "Service language star appear. Church beautiful shake believe.\nDog bill argue explain since. Likely run must system policy himself. Like among leg herself next art.\nChoose nearly be.",
          "source": "Hh.ru",
          "image": "https://placekitten.com/429/901",
          "date_publication": "2025-05-11T09:56:18.791940"
      },
      {
          "id": 2,
          "active": false,
          "external_id": "328fb59f-ed09-49a9-9030-112e7baf6ee6",
          "company_name": "May, Nelson and Brock",
          "title": "Engineer, building services",
          "salary": "6745-13570",
          "location": "Williamsville",
          "speciality": "DataScience",
          "internship": true,
          "remote": false,
          "url": "https://powell-allen.biz/",
          "description": "Likely prove total recent manager. Cause west across. Air too remain popular least well.\nWhose so west among. Fight general threat me. Pass billion human. Field adult American.",
          "source": "LinkedIn",
          "image": "https://dummyimage.com/604x811",
          "date_publication": "2025-06-03T15:42:14.352315"
      },
      {
          "id": 3,
          "active": true,
          "external_id": "8858ccb5-3e42-449f-835a-78ec21d514c6",
          "company_name": "Chaney, Harris and Burton",
          "title": "Health and safety adviser",
          "salary": "3917-10426",
          "location": "Myershaven",
          "speciality": "Python",
          "internship": true,
          "remote": false,
          "url": "https://www.floyd.com/",
          "description": "Style health beautiful husband. Gun much pick sound significant. Than social attack yeah him test.",
          "source": "Indeed",
          "image": "https://placekitten.com/762/150",
          "date_publication": "2025-06-03T19:39:09.117906"
      },
      {
          "id": 4,
          "active": true,
          "external_id": "31eaacd4-9dfb-4e26-8318-087a4662d099",
          "company_name": "Fletcher-Dodson",
          "title": "Location manager",
          "salary": "3373-14025",
          "location": "Devonbury",
          "speciality": "ML",
          "internship": false,
          "remote": true,
          "url": "https://johnson.biz/",
          "description": "Unit will arrive attorney. Sport choice lead.\nOffice what might speak. Better financial behind identify party compare behind century. Sport consumer learn consider listen budget run.",
          "source": "LinkedIn",
          "image": "https://placekitten.com/630/747",
          "date_publication": "2025-05-29T00:57:33.285513"
      },
      {
          "id": 5,
          "active": false,
          "external_id": "141b3410-888f-496b-a11a-bea999cf0393",
          "company_name": "Clark-Mcmahon",
          "title": "Tour manager",
          "salary": "3782-11225",
          "location": "Port Laurenland",
          "speciality": "ML",
          "internship": false,
          "remote": true,
          "url": "http://gilbert.net/",
          "description": "Message picture security gas. Send cause prepare claim let add.\nSet city professor.\nMachine any experience explain product. Go nature same. Herself Republican summer movement little.",
          "source": "Indeed",
          "image": "https://placekitten.com/402/602",
          "date_publication": "2025-05-28T03:33:36.046040"
      },
      {
          "id": 6,
          "active": false,
          "external_id": "0f66775b-34d3-4840-bda4-2e031736c1a5",
          "company_name": "Moss-Scott",
          "title": "Administrator",
          "salary": "4189-10073",
          "location": "West Dennisfurt",
          "speciality": "JS",
          "internship": true,
          "remote": true,
          "url": "http://www.beck.com/",
          "description": "To send in would son response. Pressure better film scene trip. Operation per we race interesting.\nRate clear society safe federal approach tell. Must fear really soon space.",
          "source": "LinkedIn",
          "image": "https://placekitten.com/25/788",
          "date_publication": "2025-05-21T18:17:31.563741"
      },
      {
          "id": 7,
          "active": true,
          "external_id": "4f76b422-b423-43e9-986d-4bc9bce48121",
          "company_name": "Wright-Strong",
          "title": "Museum/gallery conservator",
          "salary": "3839-13976",
          "location": "Williamfurt",
          "speciality": "Java",
          "internship": false,
          "remote": false,
          "url": "http://davis.org/",
          "description": "Recognize issue possible. Computer employee company really not purpose guess office. History situation majority best.\nAssume act argue. Meet debate boy mouth exist business.",
          "source": "Indeed",
          "image": "https://placekitten.com/977/465",
          "date_publication": "2025-05-09T03:23:17.759479"
      }
  ],
  "total": 17,
  "skip": 0,
  "limit": 7
}